from enum import IntEnum, IntFlag

MAGIC = b"RAVE"
PROTOCOL_VERSION = 1
MAX_DATAGRAM_SIZE = 512
SESSION_ID_SIZE = 16
MASTER_KEY_SIZE = 32
HMAC_SIZE = 32
ZERO_SESSION = bytes(SESSION_ID_SIZE)

COMMA_ADDRESS = "10.77.0.2"
RAVE_ADDRESS = "10.77.0.1"
RUNTIME_PORT = 47771
PAIRING_PORT = 47772

VEHICLE_STATE_HZ = 50.0
STATUS_HEARTBEAT_HZ = 10.0
PAIRING_PROBE_HZ = 2.0
SESSION_CHALLENGE_HZ = 5.0
PAIRING_WINDOW_NS = 60_000_000_000
STALE_NS = 150_000_000
WAITING_NS = 2_000_000_000
MAX_RECEIVE_DRAIN = 16


class MessageType(IntEnum):
  SESSION_CHALLENGE = 1
  SESSION_ACK = 2
  VEHICLE_STATE = 3
  RAVE_STATE = 4
  PAIR_PROBE = 16
  PAIR_OFFER = 17
  PAIR_KEY_INSTALL = 18
  PAIR_KEY_CONFIRM = 19
  PAIR_COMPLETE = 20
  PAIR_CANCEL = 21


class PacketFlags(IntFlag):
  NONE = 0


class WireGear(IntEnum):
  UNKNOWN = 0
  PARK = 1
  REVERSE = 2
  NEUTRAL = 3
  DRIVE = 4
  SPORT = 5
  LOW = 6
  BRAKE = 7
  ECO = 8
  MANUAL = 9


class RaveHealth(IntEnum):
  UNKNOWN = 0
  OK = 1
  DEGRADED = 2
  FAULT = 3


class LaneState(IntEnum):
  UNKNOWN = 0
  CLEAR = 1
  OCCUPIED = 2


class ThreatLevel(IntEnum):
  NONE = 0
  WATCH = 1
  WARNING = 2


class VehicleFlags(IntFlag):
  STEERING_PRESSED = 1 << 0
  LEFT_BLINKER = 1 << 1
  RIGHT_BLINKER = 1 << 2
  BRAKE_PRESSED = 1 << 3
  STANDSTILL = 1 << 4
  LEFT_BLINDSPOT = 1 << 5
  RIGHT_BLINDSPOT = 1 << 6
  CAN_VALID = 1 << 7
  CAN_TIMEOUT = 1 << 8
